/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as EnforcementRouteImport } from './routes/enforcement'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BrowserAgentRouteImport } from './routes/browser-agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCertIdRouteImport } from './routes/verify.$certId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementRoute = EnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserAgentRoute = BrowserAgentRouteImport.update({
  id: '/browser-agent',
  path: '/browser-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertIdRoute = VerifyCertIdRouteImport.update({
  id: '/verify/$certId',
  path: '/verify/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/browser-agent': typeof BrowserAgentRoute
  '/certificates': typeof CertificatesRoute
  '/elite': typeof EliteRoute
  '/enforcement': typeof EnforcementRoute
  '/identity': typeof IdentityRoute
  '/matching': typeof MatchingRoute
  '/monitoring': typeof MonitoringRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/violations': typeof ViolationsRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/verify/$certId': typeof VerifyCertIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/browser-agent': typeof BrowserAgentRoute
  '/certificates': typeof CertificatesRoute
  '/elite': typeof EliteRoute
  '/enforcement': typeof EnforcementRoute
  '/identity': typeof IdentityRoute
  '/matching': typeof MatchingRoute
  '/monitoring': typeof MonitoringRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/violations': typeof ViolationsRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/verify/$certId': typeof VerifyCertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/browser-agent': typeof BrowserAgentRoute
  '/certificates': typeof CertificatesRoute
  '/elite': typeof EliteRoute
  '/enforcement': typeof EnforcementRoute
  '/identity': typeof IdentityRoute
  '/matching': typeof MatchingRoute
  '/monitoring': typeof MonitoringRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/violations': typeof ViolationsRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/verify/$certId': typeof VerifyCertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/browser-agent'
    | '/certificates'
    | '/elite'
    | '/enforcement'
    | '/identity'
    | '/matching'
    | '/monitoring'
    | '/registry'
    | '/settings'
    | '/violations'
    | '/youtube'
    | '/api/chat'
    | '/verify/$certId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/browser-agent'
    | '/certificates'
    | '/elite'
    | '/enforcement'
    | '/identity'
    | '/matching'
    | '/monitoring'
    | '/registry'
    | '/settings'
    | '/violations'
    | '/youtube'
    | '/api/chat'
    | '/verify/$certId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/browser-agent'
    | '/certificates'
    | '/elite'
    | '/enforcement'
    | '/identity'
    | '/matching'
    | '/monitoring'
    | '/registry'
    | '/settings'
    | '/violations'
    | '/youtube'
    | '/api/chat'
    | '/verify/$certId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BrowserAgentRoute: typeof BrowserAgentRoute
  CertificatesRoute: typeof CertificatesRoute
  EliteRoute: typeof EliteRoute
  EnforcementRoute: typeof EnforcementRoute
  IdentityRoute: typeof IdentityRoute
  MatchingRoute: typeof MatchingRoute
  MonitoringRoute: typeof MonitoringRoute
  RegistryRoute: typeof RegistryRoute
  SettingsRoute: typeof SettingsRoute
  ViolationsRoute: typeof ViolationsRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiChatRoute: typeof ApiChatRoute
  VerifyCertIdRoute: typeof VerifyCertIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement': {
      id: '/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof EnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser-agent': {
      id: '/browser-agent'
      path: '/browser-agent'
      fullPath: '/browser-agent'
      preLoaderRoute: typeof BrowserAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certId': {
      id: '/verify/$certId'
      path: '/verify/$certId'
      fullPath: '/verify/$certId'
      preLoaderRoute: typeof VerifyCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BrowserAgentRoute: BrowserAgentRoute,
  CertificatesRoute: CertificatesRoute,
  EliteRoute: EliteRoute,
  EnforcementRoute: EnforcementRoute,
  IdentityRoute: IdentityRoute,
  MatchingRoute: MatchingRoute,
  MonitoringRoute: MonitoringRoute,
  RegistryRoute: RegistryRoute,
  SettingsRoute: SettingsRoute,
  ViolationsRoute: ViolationsRoute,
  YoutubeRoute: YoutubeRoute,
  ApiChatRoute: ApiChatRoute,
  VerifyCertIdRoute: VerifyCertIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
