/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as ThreatScannerRouteImport } from './routes/threat-scanner'
import { Route as ThreatRadarRouteImport } from './routes/threat-radar'
import { Route as TakedownRouteImport } from './routes/takedown'
import { Route as SocialMonitoringRouteImport } from './routes/social-monitoring'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReputationScoreRouteImport } from './routes/reputation-score'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as NewsMonitoringRouteImport } from './routes/news-monitoring'
import { Route as MonitoringJobsRouteImport } from './routes/monitoring-jobs'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as ImpersonationRouteImport } from './routes/impersonation'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as EnforcementRouteImport } from './routes/enforcement'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as DeepfakeRouteImport } from './routes/deepfake'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BrowserAgentRouteImport } from './routes/browser-agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AgentConsoleRouteImport } from './routes/agent-console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCertIdRouteImport } from './routes/verify.$certId'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicYoutubeOauthCallbackRouteImport } from './routes/api/public/youtube-oauth-callback'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksDispatchMonitoringRouteImport } from './routes/api/public/hooks/dispatch-monitoring'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatScannerRoute = ThreatScannerRouteImport.update({
  id: '/threat-scanner',
  path: '/threat-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatRadarRoute = ThreatRadarRouteImport.update({
  id: '/threat-radar',
  path: '/threat-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TakedownRoute = TakedownRouteImport.update({
  id: '/takedown',
  path: '/takedown',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMonitoringRoute = SocialMonitoringRouteImport.update({
  id: '/social-monitoring',
  path: '/social-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReputationScoreRoute = ReputationScoreRouteImport.update({
  id: '/reputation-score',
  path: '/reputation-score',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsMonitoringRoute = NewsMonitoringRouteImport.update({
  id: '/news-monitoring',
  path: '/news-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringJobsRoute = MonitoringJobsRouteImport.update({
  id: '/monitoring-jobs',
  path: '/monitoring-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonationRoute = ImpersonationRouteImport.update({
  id: '/impersonation',
  path: '/impersonation',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementRoute = EnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepfakeRoute = DeepfakeRouteImport.update({
  id: '/deepfake',
  path: '/deepfake',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserAgentRoute = BrowserAgentRouteImport.update({
  id: '/browser-agent',
  path: '/browser-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentConsoleRoute = AgentConsoleRouteImport.update({
  id: '/agent-console',
  path: '/agent-console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertIdRoute = VerifyCertIdRouteImport.update({
  id: '/verify/$certId',
  path: '/verify/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicYoutubeOauthCallbackRoute =
  ApiPublicYoutubeOauthCallbackRouteImport.update({
    id: '/api/public/youtube-oauth-callback',
    path: '/api/public/youtube-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDispatchMonitoringRoute =
  ApiPublicHooksDispatchMonitoringRouteImport.update({
    id: '/api/public/hooks/dispatch-monitoring',
    path: '/api/public/hooks/dispatch-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-console': typeof AgentConsoleRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/browser-agent': typeof BrowserAgentRoute
  '/certificates': typeof CertificatesRoute
  '/deepfake': typeof DeepfakeRoute
  '/elite': typeof EliteRoute
  '/enforcement': typeof EnforcementRoute
  '/identity': typeof IdentityRoute
  '/impersonation': typeof ImpersonationRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/monitoring': typeof MonitoringRoute
  '/monitoring-jobs': typeof MonitoringJobsRoute
  '/news-monitoring': typeof NewsMonitoringRoute
  '/registry': typeof RegistryRoute
  '/reputation-score': typeof ReputationScoreRoute
  '/settings': typeof SettingsRoute
  '/social-monitoring': typeof SocialMonitoringRoute
  '/takedown': typeof TakedownRoute
  '/threat-radar': typeof ThreatRadarRoute
  '/threat-scanner': typeof ThreatScannerRoute
  '/violations': typeof ViolationsRoute
  '/youtube': typeof YoutubeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/youtube-oauth-callback': typeof ApiPublicYoutubeOauthCallbackRoute
  '/api/public/hooks/dispatch-monitoring': typeof ApiPublicHooksDispatchMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-console': typeof AgentConsoleRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/browser-agent': typeof BrowserAgentRoute
  '/certificates': typeof CertificatesRoute
  '/deepfake': typeof DeepfakeRoute
  '/elite': typeof EliteRoute
  '/enforcement': typeof EnforcementRoute
  '/identity': typeof IdentityRoute
  '/impersonation': typeof ImpersonationRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/monitoring': typeof MonitoringRoute
  '/monitoring-jobs': typeof MonitoringJobsRoute
  '/news-monitoring': typeof NewsMonitoringRoute
  '/registry': typeof RegistryRoute
  '/reputation-score': typeof ReputationScoreRoute
  '/settings': typeof SettingsRoute
  '/social-monitoring': typeof SocialMonitoringRoute
  '/takedown': typeof TakedownRoute
  '/threat-radar': typeof ThreatRadarRoute
  '/threat-scanner': typeof ThreatScannerRoute
  '/violations': typeof ViolationsRoute
  '/youtube': typeof YoutubeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/youtube-oauth-callback': typeof ApiPublicYoutubeOauthCallbackRoute
  '/api/public/hooks/dispatch-monitoring': typeof ApiPublicHooksDispatchMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-console': typeof AgentConsoleRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/browser-agent': typeof BrowserAgentRoute
  '/certificates': typeof CertificatesRoute
  '/deepfake': typeof DeepfakeRoute
  '/elite': typeof EliteRoute
  '/enforcement': typeof EnforcementRoute
  '/identity': typeof IdentityRoute
  '/impersonation': typeof ImpersonationRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/monitoring': typeof MonitoringRoute
  '/monitoring-jobs': typeof MonitoringJobsRoute
  '/news-monitoring': typeof NewsMonitoringRoute
  '/registry': typeof RegistryRoute
  '/reputation-score': typeof ReputationScoreRoute
  '/settings': typeof SettingsRoute
  '/social-monitoring': typeof SocialMonitoringRoute
  '/takedown': typeof TakedownRoute
  '/threat-radar': typeof ThreatRadarRoute
  '/threat-scanner': typeof ThreatScannerRoute
  '/violations': typeof ViolationsRoute
  '/youtube': typeof YoutubeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/youtube-oauth-callback': typeof ApiPublicYoutubeOauthCallbackRoute
  '/api/public/hooks/dispatch-monitoring': typeof ApiPublicHooksDispatchMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-console'
    | '/assistant'
    | '/auth'
    | '/browser-agent'
    | '/certificates'
    | '/deepfake'
    | '/elite'
    | '/enforcement'
    | '/identity'
    | '/impersonation'
    | '/matching'
    | '/mcp'
    | '/monitoring'
    | '/monitoring-jobs'
    | '/news-monitoring'
    | '/registry'
    | '/reputation-score'
    | '/settings'
    | '/social-monitoring'
    | '/takedown'
    | '/threat-radar'
    | '/threat-scanner'
    | '/violations'
    | '/youtube'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/search'
    | '/verify/$certId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/youtube-oauth-callback'
    | '/api/public/hooks/dispatch-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-console'
    | '/assistant'
    | '/auth'
    | '/browser-agent'
    | '/certificates'
    | '/deepfake'
    | '/elite'
    | '/enforcement'
    | '/identity'
    | '/impersonation'
    | '/matching'
    | '/mcp'
    | '/monitoring'
    | '/monitoring-jobs'
    | '/news-monitoring'
    | '/registry'
    | '/reputation-score'
    | '/settings'
    | '/social-monitoring'
    | '/takedown'
    | '/threat-radar'
    | '/threat-scanner'
    | '/violations'
    | '/youtube'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/search'
    | '/verify/$certId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/youtube-oauth-callback'
    | '/api/public/hooks/dispatch-monitoring'
  id:
    | '__root__'
    | '/'
    | '/agent-console'
    | '/assistant'
    | '/auth'
    | '/browser-agent'
    | '/certificates'
    | '/deepfake'
    | '/elite'
    | '/enforcement'
    | '/identity'
    | '/impersonation'
    | '/matching'
    | '/mcp'
    | '/monitoring'
    | '/monitoring-jobs'
    | '/news-monitoring'
    | '/registry'
    | '/reputation-score'
    | '/settings'
    | '/social-monitoring'
    | '/takedown'
    | '/threat-radar'
    | '/threat-scanner'
    | '/violations'
    | '/youtube'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/search'
    | '/verify/$certId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/youtube-oauth-callback'
    | '/api/public/hooks/dispatch-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentConsoleRoute: typeof AgentConsoleRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BrowserAgentRoute: typeof BrowserAgentRoute
  CertificatesRoute: typeof CertificatesRoute
  DeepfakeRoute: typeof DeepfakeRoute
  EliteRoute: typeof EliteRoute
  EnforcementRoute: typeof EnforcementRoute
  IdentityRoute: typeof IdentityRoute
  ImpersonationRoute: typeof ImpersonationRoute
  MatchingRoute: typeof MatchingRoute
  McpRoute: typeof McpRoute
  MonitoringRoute: typeof MonitoringRoute
  MonitoringJobsRoute: typeof MonitoringJobsRoute
  NewsMonitoringRoute: typeof NewsMonitoringRoute
  RegistryRoute: typeof RegistryRoute
  ReputationScoreRoute: typeof ReputationScoreRoute
  SettingsRoute: typeof SettingsRoute
  SocialMonitoringRoute: typeof SocialMonitoringRoute
  TakedownRoute: typeof TakedownRoute
  ThreatRadarRoute: typeof ThreatRadarRoute
  ThreatScannerRoute: typeof ThreatScannerRoute
  ViolationsRoute: typeof ViolationsRoute
  YoutubeRoute: typeof YoutubeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  VerifyCertIdRoute: typeof VerifyCertIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicYoutubeOauthCallbackRoute: typeof ApiPublicYoutubeOauthCallbackRoute
  ApiPublicHooksDispatchMonitoringRoute: typeof ApiPublicHooksDispatchMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-scanner': {
      id: '/threat-scanner'
      path: '/threat-scanner'
      fullPath: '/threat-scanner'
      preLoaderRoute: typeof ThreatScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-radar': {
      id: '/threat-radar'
      path: '/threat-radar'
      fullPath: '/threat-radar'
      preLoaderRoute: typeof ThreatRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takedown': {
      id: '/takedown'
      path: '/takedown'
      fullPath: '/takedown'
      preLoaderRoute: typeof TakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-monitoring': {
      id: '/social-monitoring'
      path: '/social-monitoring'
      fullPath: '/social-monitoring'
      preLoaderRoute: typeof SocialMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reputation-score': {
      id: '/reputation-score'
      path: '/reputation-score'
      fullPath: '/reputation-score'
      preLoaderRoute: typeof ReputationScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-monitoring': {
      id: '/news-monitoring'
      path: '/news-monitoring'
      fullPath: '/news-monitoring'
      preLoaderRoute: typeof NewsMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring-jobs': {
      id: '/monitoring-jobs'
      path: '/monitoring-jobs'
      fullPath: '/monitoring-jobs'
      preLoaderRoute: typeof MonitoringJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonation': {
      id: '/impersonation'
      path: '/impersonation'
      fullPath: '/impersonation'
      preLoaderRoute: typeof ImpersonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement': {
      id: '/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof EnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deepfake': {
      id: '/deepfake'
      path: '/deepfake'
      fullPath: '/deepfake'
      preLoaderRoute: typeof DeepfakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser-agent': {
      id: '/browser-agent'
      path: '/browser-agent'
      fullPath: '/browser-agent'
      preLoaderRoute: typeof BrowserAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-console': {
      id: '/agent-console'
      path: '/agent-console'
      fullPath: '/agent-console'
      preLoaderRoute: typeof AgentConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certId': {
      id: '/verify/$certId'
      path: '/verify/$certId'
      fullPath: '/verify/$certId'
      preLoaderRoute: typeof VerifyCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube-oauth-callback': {
      id: '/api/public/youtube-oauth-callback'
      path: '/api/public/youtube-oauth-callback'
      fullPath: '/api/public/youtube-oauth-callback'
      preLoaderRoute: typeof ApiPublicYoutubeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-monitoring': {
      id: '/api/public/hooks/dispatch-monitoring'
      path: '/api/public/hooks/dispatch-monitoring'
      fullPath: '/api/public/hooks/dispatch-monitoring'
      preLoaderRoute: typeof ApiPublicHooksDispatchMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentConsoleRoute: AgentConsoleRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BrowserAgentRoute: BrowserAgentRoute,
  CertificatesRoute: CertificatesRoute,
  DeepfakeRoute: DeepfakeRoute,
  EliteRoute: EliteRoute,
  EnforcementRoute: EnforcementRoute,
  IdentityRoute: IdentityRoute,
  ImpersonationRoute: ImpersonationRoute,
  MatchingRoute: MatchingRoute,
  McpRoute: McpRoute,
  MonitoringRoute: MonitoringRoute,
  MonitoringJobsRoute: MonitoringJobsRoute,
  NewsMonitoringRoute: NewsMonitoringRoute,
  RegistryRoute: RegistryRoute,
  ReputationScoreRoute: ReputationScoreRoute,
  SettingsRoute: SettingsRoute,
  SocialMonitoringRoute: SocialMonitoringRoute,
  TakedownRoute: TakedownRoute,
  ThreatRadarRoute: ThreatRadarRoute,
  ThreatScannerRoute: ThreatScannerRoute,
  ViolationsRoute: ViolationsRoute,
  YoutubeRoute: YoutubeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSearchRoute: ApiSearchRoute,
  VerifyCertIdRoute: VerifyCertIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicYoutubeOauthCallbackRoute: ApiPublicYoutubeOauthCallbackRoute,
  ApiPublicHooksDispatchMonitoringRoute: ApiPublicHooksDispatchMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
